### ISSUE TITLE
Provide guidance on SCA & ZAP report outputs to devs.

### ISSUE THREAD

**Issue by DavidEBest** [18F/before-you-ship#109]
As a developer, I should know what reports are required of me for ATO, and where they should be put.

What reports are needed by @NoahKunin to verify that the application was scanned and where should the developer put them?

Is there a preferred format? HTML/JSON
Should there be an accompanying report describing false positives?

**Comment by afeld** [comment]
> where should the developer put them?

[This folder](https://drive.google.com/a/gsa.gov/folderview?id=0BynIxtx-CfkdckljM3BPSkdQT1U&usp=sharing), which is mentioned in [the ATO checklist](https://drive.google.com/a/gsa.gov/folderview?id=0BynIxtx-CfkdckljM3BPSkdQT1U&usp=sharing).

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
