### ISSUE TITLE
point to new compliance repo

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#141]
Per @jezhumble's [Slack post](https://18f.slack.com/files/jezhumble/F0S1TMW2V/DevOps_becomes_Infrastructure_Engineering), ATO requests should now move to https://github.com/18F/compliance. Maybe we convert [the checklist](https://pages.18f.gov/before-you-ship/ato/checklist/) to an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) there?

**Comment by jezhumble** [comment]
I think that's a great idea!

**Comment by DavidEBest** [comment]
The ATO issues are still going to infrastructure. Should they be? If so, let's close this issue.

**Comment by NoahKunin** [comment]
Looks like this never got done, because no one was assigned. Let's make sure we're good at assigning things.

I'm assigning @jezhumble and @afeld to quickly convene and re-assess if the decision makes sense or not anymore. Please decide by Tuesday - thanks!

**Comment by afeld** [comment]
Looks like ATOs are going to continue being tracked in the Infrastructure repo.

https://github.com/18F/Infrastructure/projects/1

@NoahKunin Cool if we delete the compliance repo?

https://github.com/18F/compliance
