### ISSUE TITLE
Improve description of the level of alerts from ZAP.

### ISSUE THREAD

**Issue by DavidEBest** [18F/before-you-ship#153]
https://pages.18f.gov/before-you-ship/security/scanning/#alerts should be expanded to provide more detail about what qualifies an alert as high/medium/low.

**Comment by afeld** [comment]
Closing as stale.

**Comment by its-a-lisa** [comment]
Deleting as stale based on the TTS Tech Portfolio Deep Grooming session from 3/30/20; if you have any questions, comments or concerns, please let us know either in the #infrastructure or #tts-tech-portfolio slack channels
