### ISSUE TITLE
Pull in Before You Ship Brainstorming content

### ISSUE THREAD

**Issue by DavidEBest** [18F/before-you-ship#155]
https://docs.google.com/document/d/1rw01PX_NPeOK13sThLqI3EPyNwYijD0BJDUGQTdlDpA/edit

Broken out from https://trello.com/c/6zI9JUEK/13-consolidate-ato-documentation.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
