### ISSUE TITLE
Consider how to codify what is law vs. regulation vs. guidance, etc.

### ISSUE THREAD

**Issue by DavidEBest** [18F/before-you-ship#156]
The relationship between what is law vs. regulation vs. guidance in the existing ATO process is murky. How can we clear that up and represent it effectively?

**Comment by afeld** [comment]
The [18F Engineering Guide](https://engineering.18f.gov/) does a nice job of this:

![Screen Shot 2020-03-11 at 12 55 48 PM](https://user-images.githubusercontent.com/86842/76442663-a5bc1600-6397-11ea-86ea-34157f724bc3.png)

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
