### ISSUE TITLE
Revisit Node static code analysis recommendation with the progress made to snyk.io

### ISSUE THREAD

**Issue by DavidEBest** [18F/before-you-ship#160]
We first evaluated snyk.io more than six months ago. The project has come a long way since then. We should re-evaluate and potentially update our recommendations based on findings.

**Comment by afeld** [comment]
Per @NoahKunin, "this is [now] what we use for Node apps."

**Comment by afeld** [comment]
A couple of new ones:

* https://www.bithound.io/
* https://jacks.codiscope.com/landing.html

**Comment by afeld** [comment]
More languages supported: https://support.snyk.io/getting-started/languages-support

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
