### ISSUE TITLE
Move language/framework-specific configuration suggestions to FISMA Ready org

### ISSUE THREAD

**Issue by DavidEBest** [18F/before-you-ship#162]
- https://pages.18f.gov/before-you-ship/security/frameworks/
- https://github.com/fisma-ready

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
