### ISSUE TITLE
consolidate information about selecting the Level

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#166]
There are a few pages that have overlap:
- https://pages.18f.gov/before-you-ship/ato/walkthrough/#step-2--select-controls
- https://pages.18f.gov/before-you-ship/ato/categorize/
- https://pages.18f.gov/before-you-ship/ato/levels/

**Comment by hollyallen** [comment]
https://pages.18f.gov/before-you-ship/ato/categorize/ is gone, whew.

https://pages.18f.gov/before-you-ship/ato/walkthrough/#step-2--select-controls has been shortened. Most of that info is now in https://pages.18f.gov/before-you-ship/ato/walkthrough/#step-2--select-controls

I'm going to say this is no longer relavent.
