### ISSUE TITLE
Before you ship should be exportable as PDF or an ebook format

### ISSUE THREAD

**Issue by pburkholder** [18F/before-you-ship#184]
I'd like to sit and read this content, but being trapped in my browser is not the experience I need to digest this material.

As an interested  consumer of this content I would like to read it as a complete document, offline. So the site should offer an option to download as .pdf, .mobi or .ebook, etc...

Thanks, Peter

**Comment by afeld** [comment]
Hmm. My gut reaction is that nothing in this site is a long narrative form that would lend itself well to a book-like format...there's a lot of cross-linking between pages, and jumping out to external sites...and thus a "wontfix". That being said, if you want to give it a try, you might look into something like

https://github.com/fauno/jekyll-pandoc-multiple-formats

Closing for now, but if someone else on the team disagrees, feel free to re-open!
