### ISSUE TITLE
What does `internal: true` mean in the config YAML?

### ISSUE THREAD

**Issue by NoahKunin** [18F/before-you-ship#188]
The whole guide is public...?

**Comment by afeld** [comment]
Right...that's for the Guides style gem, which needs that in there for internal links for some reason. Nothing to do with the site/pages being accessible from the outside world or not.

/cc https://github.com/18F/guides-style/issues/69

**Comment by NoahKunin** [comment]
Ah, it adds the little icon so external entities know they will get a denied message if they try and click right? Thanks!
