### ISSUE TITLE
Lightweight interviews with a couple users to help identify overall guide issues

### ISSUE THREAD

**Issue by brittag** [18F/before-you-ship#189]
Noting a thing I'm working on as part of cloud.gov HighBar:

In order to get a better overall understanding of how to improve our ATO process documentation (both improving overall structure and smaller specific issues), we should do short interviews with a couple of 18F staff (in product and engineering) who have recently needed to use the Before You Ship guide.

Improving this guide supports the cloud.gov team's work on reducing time-to-ATO both inside and outside 18F. This is just a bit of user-centered checking for incremental progress.

Tasks:

* Interview a PM (30 min), put together notes about their experience.
* Interview an engineer (30 min), put together notes about their experience.
* Spend 30-60 min fixing anything small/obvious/easy that would have smoothed our their experiences, and file a few issues tracking further things that should be improved.

Acceptance criteria:

- [x] Notes about these interviews are available within 18F's Google Drive.
- [x] We've identified a few useful next steps based on those interviews, and either made those changes or documented them as issues.

**Comment by afeld** [comment]
In case you need to find more people:

https://github.com/18F/Infrastructure/issues?q=is%3Aissue+ato+in%3Atitle+sort%3Aupdated-desc

**Comment by brittag** [comment]
I put up notes [over here in the cloud.gov research folder](https://drive.google.com/drive/u/0/folders/0B1cewEqKcWCbQ2s2UjlRUkFCVUk)! Next I'm going to think more about how to break down what I learned into specific prioritized tasks.

**Comment by brittag** [comment]
Filed so far based on this research: https://github.com/18F/before-you-ship/issues/190 (Help readers understand where to ask questions) + https://github.com/18F/before-you-ship/issues/191 (The guide should present one consistent set of steps toward ATO).

**Comment by brittag** [comment]
Going to close this issue as having served its purpose for now! We can fix more things based on the research (and potentially interview another engineer or two who has worked on getting an ATO at 18F) when we decide that's the best next step.
