### ISSUE TITLE
The guide should present one consistent set of steps toward ATO

### ISSUE THREAD

**Issue by brittag** [18F/before-you-ship#191]
In order to follow the BYS guide without confusion, 18F staff members who are working on getting an ATO should be able to follow one consistent/authoritative set of steps. Currently the BYS guide has a few similar but not-quite-aligned efforts at steps toward shipping/ATO, which is a bit confusing:
1. https://pages.18f.gov/before-you-ship/
2. https://pages.18f.gov/before-you-ship/ato/walkthrough/
3. https://pages.18f.gov/before-you-ship/ato/checklist/

A reasonable way to improve this might be to reshape the walkthrough to match the checklist (as a more detailed version of the checklist), and then fix up the homepage to be less redundant (and just link to the walkthrough).

This is related to https://github.com/18F/before-you-ship/issues/166 ("consolidate information about selecting the Level").

Acceptance criteria:
- [x] The checklist steps and walkthrough steps in the BYS guide are aligned.
- [x] The BYS homepage isn't redundant with the checklist or walkthrough.

**Comment by brittag** [comment]
There's also a fourth checklist for "before you ship" type info (with some overlap with ATO requirements): https://pages.18f.gov/before-you-ship/infrastructure/good-production-practices/

**Comment by its-a-lisa** [comment]
This issue should be closed because the walkthrough page is 404 error now, making this issue overcome; I do think that the checklist and other elements need to be reviewed; but better off closing this and opening a new issue for it.
