### ISSUE TITLE
As a user, I want to know what a LATO is

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#192]
We mention it on https://pages.18f.gov/before-you-ship/ato/types/ but don't really explain it.

/cc @toolness

**Comment by brittag** [comment]
Is the authoritative expansion of LATO "Limited Authority to Operate" or "Lightweight Authority to Operate"? "Lightweight" looked authoritative to me, so I fixed an instance of "Limited" in https://github.com/18F/before-you-ship/pull/193 - but please correct that if I'm wrong.

**Comment by afeld** [comment]
Yep, the latter is correct.

**Comment by brittag** [comment]
Noting that https://github.com/18F/GSA-Certifications/blob/master/LATO.yaml may be helpful for this.

**Comment by brittag** [comment]
And the eRegs N&C files may be helpful as well: https://github.com/18F/epa-notice/blob/master/opencontrol.yaml + https://github.com/18F/epa-notice/blob/master/compliance/component.yaml

**Comment by afeld** [comment]
https://gsablogs.gsa.gov/innovation/2014/12/10/it-security-security-in-an-agile-development-cloud-world-by-kurt-garbars/

**Comment by afeld** [comment]
Closed by https://github.com/18F/before-you-ship/pull/235.
