### ISSUE TITLE
Add more explanation to the System Security Plan page (or update it)

### ISSUE THREAD

**Issue by brittag** [18F/before-you-ship#197]
In order for 18F staff to confidently fill out their [Before You Ship ATO checklist](https://pages.18f.gov/before-you-ship/ato/checklist/)'s [System Security Plan](https://pages.18f.gov/before-you-ship/ato/ssp/) step, they need a full explanation for what to do during that step.

The [current page](https://pages.18f.gov/before-you-ship/ato/ssp/) provides a template that asks people to fill out information such as `system-type`, `level-of-identity-assurance`, `components`, and `controls`, but the page doesn't provide information about what those fields means or how to fill them out.

This page should link to enough information so that a person can learn how to fill this out and check that checkbox, or the checklist should be updated to reflect this requirement better.

(This is based on a followup comment from an engineer after the [lightweight user interviews](https://github.com/18F/before-you-ship/issues/189).)

**Comment by brittag** [comment]
Also, the two examples linked at the bottom of the SSP page (ATF eRegs and EKIP API) are from several months ago and may not be up-to-date/helpful.

**Comment by afeld** [comment]
The plan is for it to go away in favor of Compliance Masonry: https://github.com/opencontrol/compliance-masonry/issues/1
