### ISSUE TITLE
Add section on splitting production and development dependencies

### ISSUE THREAD

**Issue by jseppi** [18F/before-you-ship#209]
Similar to https://github.com/18F/before-you-ship/pull/199, adding a section on separation of production and deployment dependencies would probably be good to have. Node (and I think Ruby) have good support for doing this baked into their package management tools (like `dependencies` and `devDependencies` in `package.json` for node).
Python, on the other hand, doesn't seem to have a standard or built-in way of separating dependencies.

As part of CALC 2.0's ATO process, we recently did this by creating two distinct requirements files (see this PR: https://github.com/18F/calc/pull/681):
- `requirements-dev.txt` for dev/testing dependencies and 
- `requirements.txt` for production dependencies

One nice way of handling multiple requirements files is that you can include requirements files inside of others, as done here: https://github.com/18F/calc/pull/681/files#diff-f4c265073ea4274a80eca85440875e56R2

**Comment by afeld** [comment]
I'd actually say this is a better fit for the [Development Guide](https://github.com/18F/development-guide) or possibly the [cloud.gov docs](https://docs.cloud.gov/). Closing this issue, but feel free to open wherever you think it makes more sense!

**Comment by jseppi** [comment]
Aw :(

Thought it was relevant here since it was recommended (though not mandated) we do it in support of getting an ATO for CALC 2.0. Refer to the third bullet point in this comment by @NoahKunin: https://github.com/18F/Infrastructure/issues/649#issuecomment-245316653

**Comment by afeld** [comment]
Hmm, ok...fair enough. I would still be in favor of those recommendations living elsewhere, and linking to them from Before You Ship, since it's _more_ of a general best practice than something strictly tied to security, compliance, availability etc. That being said, I don't feel super strongly.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
