### ISSUE TITLE
who owns this repo?  what are the guidelines for accepting PRs?

### ISSUE THREAD

**Issue by ultrasaurus** [18F/before-you-ship#21]
I found a bug and noticed there's a PR from two days ago.  We should add something to the CONTRIBUTING.md that sets some guidelines on how to help, like:  https://github.com/18F/midas/blob/devel/CONTRIBUTING.md#reviewing-pull-requests

Proposed text:

Except for critical, urgent or very small fixes, leave pull requests open for most of the day or overnight if something comes in late in the day, so that multiple people have the chance to review/comment. Anyone who reviews a pull request should leave a note to let others know that someone has looked at it. For larger edits, we like to have a +1 from someone who has experience with the topic. Please note if you actually can verify the information, such as "sounds right" or "nice clarification" -- a +1 by itself will typically be interpreted as your thinking its a good idea, but not having reviewed in detail.

Anyone on the 18F ???? team who believes the change is good can (and should) merge pull requests that have been reviewed and are older than 1 day.  A committer can both review and merge if they are not the author of the pull request.

**Comment by mbland** [comment]
I thought @afeld started it, but I guess it was actually @leahbannon. I know she and @hollyallen have been pouring more attention into it lately. There's been a bit of chatter on 18F/cloud-foundry-notes#92 as well.

The CONTRIBUTING suggestion sounds good. File a PR?

**Comment by awfrancisco** [comment]
I'm free to do editing on guides, but I've been holding off on this one pending new content, as @mbland said above.

**Comment by afeld** [comment]
This seems like more of an issue for changing our CONTRIBUTING.md template over at https://github.com/18F/open-source-policy. Closing, but feel free to reopen if I'm misunderstanding.

**Comment by ultrasaurus** [comment]
Yes, the template should be changed to include some draft content on how PRs get merged, but this repo also needs something like this...

## Accepting/Merging Pull Requests

Typically pull Requests should be merged by a different person who opened them, ensuring that at least one other person has eyes on it.  If you see an open pull request that you agree with add a comment and :+1: -- a :+1: by itself merely indicates
that you like the direction and think it is a good idea, if you have reviewed the code or text, please comment that you have done so.  Unless it is a very small change or critical fix, pull requests should remain open for 24 hours to give everyone on the team a chance to chime in.

When a pull request is merged to staging it is automatically deployed to [https://pages.18f.gov/before-you-ship/(https://pages.18f.gov/before-you-ship/)

**Comment by afeld** [comment]
Are you opening this issue on other repositories as well, or just this one? I guess I'm still not understanding what why the process here would be different from any other repository, so would prefer to have the conversation in the canonical source.

Anyone else have thoughts on this?

**Comment by afeld** [comment]
Closing as stale, though I'm happy to continue the conversation.
