### ISSUE TITLE
ATO control docs link to 18F/https, but that repo is marked deprecated

### ISSUE THREAD

**Issue by jacobian** [18F/before-you-ship#212]
_[Credit for noticing this goes to David Kane-Parry, sent to me over email]_

https://pages.18f.gov/before-you-ship/ato/controls/#https-everywhere links to https://github.com/18F/https, but that page is marked deprecated. I took a spin around looking for documentation about how we're doing https now, but I can't seem to find it. What's our current guidance on https?

**Comment by afeld** [comment]
@konklone ^

**Comment by konklone** [comment]
@jacobian I'm not sure we have any. That repo is deprecated because it was optimized for a pre-cloud.gov world. Whatever cloud.gov does now for TLS certificates is what we should document.

**Comment by its-a-lisa** [comment]
Closing as stale since the original page referenced is no longer operational.
