### ISSUE TITLE
include static analysis tool options for Go

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#213]
...because @jcscottiii finally found one! We should first make sure that it actually works and is effective, before adding it to [the list](https://pages.18f.gov/before-you-ship/security/static-analysis/).

https://github.com/HewlettPackard/gas

**Comment by NoahKunin** [comment]
I saw that - I know we're approaching formalization on this, so CCing @dlapiduz and @cnelson so we're all on the same page (whether it's a Go app _on_ cloud.gov or in/part of cloud.gov)

**Comment by cnelson** [comment]
I think after today's conversation, we should probably just list Go under the existing Code Climate section, as Code Climate now ships `golint` and `govet` engines.

**Comment by NoahKunin** [comment]
@cnelson works for me! A cursory review just now indicates that's probably the best we'll get for now re: Go, but that Code Climate still isn't matching Brakeman/Hakiri/Gemnasium for Ruby on Rails (which is weird).

**Comment by afeld** [comment]
> `golint` and `govet`

I think those are purely style, rather than having anything related to security. I could be wrong!

**Comment by jcscottiii** [comment]
if we want a swiss army knife and more, there's [gometalinter](https://github.com/alecthomas/gometalinter) (it includes Gas too)

**Comment by afeld** [comment]
Discussions about adding golang support to

* [Dep](https://github.com/golang/dep/issues/176)
* [Gemnasium](http://support.gemnasium.com/forums/236528-general/suggestions/6018896-golang-packages)
