### ISSUE TITLE
mark 18F Pages as deprecated?

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#218]
Seems like we should be directing new 18F projects to Federalist instead...?

/cc @jezhumble @wslack

**Comment by adborden** [comment]
FWIW, I think some 18f-pages are better suited as static apps on cloud.gov. Federalist is focused on Jekyll based sites and creates friction for non-Jekyll based sites. If you've already got a built system, it's pretty easy to add a manifest.yml pointing to your build directory.

Anyway, I'd like to have a guide on _how to migrate your app from 18f-pages_ with explanation on your options and how to do that.

**Comment by jezhumble** [comment]
18f-pages is jekyll based, albeit requiring the guides-style gem installed (https://github.com/18F/guides-style) - you just start by cloning this: https://github.com/18F/guides-template.

It'd be great to spike hosting *a* guide using Federalist - I thought there was someone working on this already...

**Comment by wslack** [comment]
@adborden AFAIK Federalist does just fine for deploying HTML straight from DreamWeaver - do you mean if using Hugo or something?

**Comment by adborden** [comment]
Hmm, @wslack are there docs for it? [cg-style](https://github.com/18F/cg-style) is an npm module we use to style our cloud.gov apps but also builds a styleguide as a static site into `docs/build`. Pushing this static dir to cloud.gov or to `18f-pages` branch is pretty trivial. I'm not sure that Federalist supports that scenario (at least I couldn't figure it out).

[fec-style](https://github.com/18f/fec-style) is in a similar position.

**Comment by wslack** [comment]
@adborden fair point, it doesn't like it (missing CSS maybe <link rel="stylesheet" href="../../_theme/css/default.css?cachebust=1.0.7" type="text/css">) http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/18f/cg-style/index.html

But also, it's a fiar point that using something different than Jekyll is tough (I'm not an admin on cg-style so I couldn't tinker too much).

Given that all guides are jekyll based, though, I think it should be fine - let me know if any of the guides have a problem aside from none of their own CSS. Shawn Allen and I are setting up a way to produce a guide without relaying on the guides_style gem (and using the design standards); see an example here: https://federalist.18f.gov/preview/18f/federalist-docs/uswds/

**Comment by cmc333333** [comment]
CC @ccostino in case there's anything he'd like to add from the documentation working group's perspective.

**Comment by ccostino** [comment]
Thanks @cmc333333!  None that I can think of other than we've already been working on this kind of thing and have tested porting a guide over to Federalist (@jeremiak can speak more to this); it's very straight-forward given that they're also Jekyll-based.  The styles are the only thing that come to mind as an issue from that perspective, and the whole URL preservation problem, but only for existing guides.

Going forward we've already been recommending that folks just build them in Federalist.

Again, keeping things tied together as best I can, more discussion is happening in these spots:

* https://github.com/18F/guides/issues/46
* https://github.com/18F/Infrastructure/issues/702

**Comment by ccostino** [comment]
Ah, good point @adborden, thank you for clarifying all of that!

**Comment by wslack** [comment]
Agreed; thanks.

**Comment by ccostino** [comment]
@afeld and others on this issue:  would you mind shifting this discussion over to https://github.com/18F/guides/issues/46 to help consolidate the discussion threads taking place around all of this?  This way we can all focus our efforts and ideas in one spot to keep things manageable.

If that's agreeable I propose closing this issue in favor of the other one.
