### ISSUE TITLE
Catch 22: when can an app be made public?

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#222]
FRom @jeremiak [in Slack](https://gsa-tts.slack.com/archives/wg-documentation/p1476736887000227):

> in order to use the compliance viewer (OWASP) we need to have a live URL. but to have a live URL we need to get an ATO. And to get an ATO we need to run compliance viewer

**Comment by NoahKunin** [comment]
See https://gsa-tts.slack.com/archives/infrastructure/p1476741348002355

**Comment by afeld** [comment]
I think this is now addressed by https://before-you-ship.18f.gov/ato/types/#conditions-for-pre-assessment.
