### ISSUE TITLE
consolidate info about Personally Identifiable Information (PII)

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#226]
- https://pages.18f.gov/before-you-ship/ato/categorize/#conditions
- https://pages.18f.gov/before-you-ship/security/pii/
- https://handbook.18f.gov/research-guidelines/#managing-personally-identifiable-information-pii
- https://gsa-tts.slack.com/archives/infrastructure/p1477451785002746

We probably want to merge the second and third.

**Comment by andrewmaier** [comment]
I'm interested in learning more about whatever this becomes.

**Comment by afeld** [comment]
Per @jacobian, https://www.dhs.gov/sites/default/files/publications/privacy/Guidance/handbookforsafeguardingsensitivePII_march_2012_webversion.pdf is "the source of truth".

**Comment by andrewmaier** [comment]
Will bring this to @rspeidel later this week and report back on what might constitute a sensible plan of action given his content goals. Going to want to sync with you also, @afeld :)

**Comment by andrewmaier** [comment]
Pulling this information from the draft [CIO 2100.1K GSA Information Technology (IT) Security Policy](https://docs.google.com/document/d/1cTfUIQSBnyEa-ltToCvn_QXtAqTdqs_E0wIiXSeK3no/edit?) document:

>... systems that contain privacy act data or personally identifiable information (PII) must implement the additional privacy controls as defined in NIST SP 800-53 R4, Appendix J: Privacy Control Catalog, GSA Order CPO 1878.1 Privacy Act Program under “Information Security” and GSA Order CIO P 1878.2A, Conducting Privacy Impact Assessments (PIAs) in GSA.

**Comment by its-a-lisa** [comment]
Moved to waiting until the [BYS is merged with Handbook](https://github.com/18F/before-you-ship/issues/421)

**Comment by afeld** [comment]
Closing as stale.
