### ISSUE TITLE
Note #wg-compliance somewhere

### ISSUE THREAD

**Issue by brittag** [18F/before-you-ship#231]
TTS/18F now has #wg-compliance! ("Creating tooling, resources, and emotional support for people to get through compliance processes. Use #infrastructure for official communication around ATOs.")

We should find the right place to mention it in Before You Ship, carefully noting that it's an informal place to share knowledge across teams (rather than a source of truth).

**Comment by afeld** [comment]
Part of #190.

**Comment by its-a-lisa** [comment]
Closing because it is mentioned in [working groups handbook page](https://handbook.18f.gov/working-groups-and-guilds-101/ ) and [BYS is being moved to the handbook](https://github.com/18F/before-you-ship/issues/421)
