### ISSUE TITLE
Link to PixelLab checklist link needs updating

### ISSUE THREAD

**Issue by line47** [18F/before-you-ship#234]
The link to _pixel lab’s website pre-launch checklist_ is no longer going to the checklist as it is no longer accurate. 

The current link goes here: http://thepixellab.com.au/the-website-pre-launch-checklist/ and redirects to the pixel lab homepage

The checklist has been archived and lives here: http://archive.is/whNeM

**Comment by afeld** [comment]
Closed by #266.
