### ISSUE TITLE
ATO for static cloud.gov apps

### ISSUE THREAD

**Issue by adborden** [18F/before-you-ship#242]
I'm looking at the [ATO exception for Federalist and 18f-pages](https://github.com/18F/before-you-ship/blob/18f-pages/_pages/ato.md#ato-status-of-federalistpages-sites). I believe this should also apply to static applications hosted on cloud.gov. Can we edit the paragraph to include that?

**Comment by adborden** [comment]
That link is dead, here's the text as of today:
>  Note: Technically, static site builders are just adding a collection of pages in an existing system. Therefore, from an ATO perspective, “sites” created through Federalist or 18F Pages remain within the respective security boundary, and thus ATO.

Would this also apply to apps built with the static_buildpack on cloud.gov?

**Comment by afeld** [comment]
Not the way that ATOs are currently done, unfortunately. Would be nice for this to be the case someday!

**Comment by afeld** [comment]
(and sorry for taking so long to respond)
