### ISSUE TITLE
what is Chandika?

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#245]
https://github.com/18F/chandika

It's mentioned in the docs, but not really explained.

**Comment by fureigh** [comment]
Thanks, @afeld! To ensure this doesn't get lost: it's also mentioned in the AWS Sandbox Request form.

**Comment by its-a-lisa** [comment]
Deleting as stale based on the TTS Tech Portfolio Deep Grooming session from 3/30/20; if you have any questions, comments or concerns, please let us know either in the #infrastructure or #tts-tech-portfolio slack channels
