### ISSUE TITLE
Guidance about documentation 

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#251]
We need some guidance in this handbook about the level of detail needed in a project README.

For example, on FBI: "So I just answered a few questions from Noah about SQL and SQLAlchemy and such and it’s clear it would be really useful to the ATO process if we could document what we do post-load to the database and how SQLAlchemy builds queries (and presumably has injection protections within it)."

**Comment by afeld** [comment]
Closing as stale.
