### ISSUE TITLE
document your api

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#252]
api documentation must be available and complete before security assessment can start. don't include endpoints that aren't implemented yet. if an api key is required, document how to get one. probably more stuff too.

https://github.com/18F/api-standards

**Comment by harrisj** [comment]
Thank you. The Swagger docs are generated dynamically from annotations on API endpoints, so it should not include anything that doesn't exist. I will look into the other parts shortly. If I understand you correctly, this is a blocker that must be fixed ASAP for the ATO process to continue?

**Comment by hollyallen** [comment]
Don't worry Jacob, this ticket is to update the before you ship guide to make guidance more clear for projects. Your project's API docs got a thumbs up from Noah already.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
