### ISSUE TITLE
Guidance for system diagrams

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#254]
We need more guidance on how to create the system diagrams, especially when built on cloud.gov. The FBI project's diagram should be a good baseline going forward. The diagram cannot contradict cloud.gov's network diagram: https://diagrams.fr.cloud.gov/10-1-network.html

**Comment by afeld** [comment]
Example of details to include:

* When there should be arrows, and which direction they should point
* What parts of cloud.gov need to be represented

**Comment by hollyallen** [comment]
Partly addressed in #267 , by replacing old links to diagrams with new links to FBI and CALC diagrams. Still need to write the words as suggested by @afeld .

**Comment by afeld** [comment]
A couple other things I just realized:

* The boxes in the diagram should roughly correspond to the rows in the `Software Components` tables
* The arrows should correspond to rows in the `Ports, Protocols, and Services` tables, with labels of the format `<protocol> <port>(<T(CP) or U(DP)>) - <Purpose>`
