### ISSUE TITLE
Protected branches are required

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#255]
Pull requests for vulnerability fixes are made to protected branches in the GitHub repository. Changes must be reviewed and accepted by a different member of the project team or the System Owner.

**Comment by afeld** [comment]
We'll need to be more specific about which settings are required.

<img width="754" alt="screen shot 2017-03-04 at 5 33 50 am" src="https://cloud.githubusercontent.com/assets/86842/23578072/32799db8-009c-11e7-848b-7b65262c9de9.png">

https://help.github.com/articles/about-protected-branches/

**Comment by wslack** [comment]
oh, this is handy. I worry a bit about blocking admins from self-merges (sometimes, this is important when there are no other reviewers online). "Developers team" is also ambiguous.

**Comment by hollyallen** [comment]
Replaced "developers team" (misspelled anyway) with "project team" which should be less ambiguous.

**Comment by afeld** [comment]
Closing as stale.
