### ISSUE TITLE
Consider adding port scanning to "before ato assessment"

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#260]
Penetration testing includes port scanning. It could be useful to have project teams do port scanning before official testing in order to know what will be found and have answers for each.

**Comment by afeld** [comment]
Not sure how relevant this is for projects on cloud.gov.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
