### ISSUE TITLE
Security alerts: email alerts for critical dependency updates

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#261]
When dependency scanning tool (gemnasium for example) finds a critical security problem with a dependent library that requires a version upgrade to resolve, an email should be sent to the project team. We cannot rely on the project team reviewing gemnasium and noticing the problem.

**Comment by afeld** [comment]
Pretty sure Gemnasium (and others) do this by default. Maybe we just tell them how to check their settings?
