### ISSUE TITLE
expand the ATO issue template to include Sprinting Team steps

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#263]
The checklist currently has items that are almost all directed at the project team, but not tasks for the Sprinting Team, Security, etc. We should include these, so that there is a canonical place that can be referenced to understand the ATO process state of a system. Examples:

* RoE signed
* Scanning complete
* ATO letter out for signatures

**Comment by hollyallen** [comment]
Include: Pre-document-review-meeting between Infrastructure Lead and Project Team to go over full process.

**Comment by afeld** [comment]
There may be some overlap here with the columns of [the kanban](https://github.com/18F/Infrastructure/projects/1). We should consider what stages should be represented where (in what detail).
