### ISSUE TITLE
update information about Federalist re: ATO

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#272]
Not sure that this information is still accurate, given the whole [S3 bucket ATO](https://github.com/18F/Infrastructure/issues/779) thing:

https://pages.18f.gov/before-you-ship/ato/#ato-status-of-federalistpages-sites

/cc @wslack

**Comment by wslack** [comment]
That's true for federalist (though we could add that there's a required scanning process); not sure about pages.

**Comment by afeld** [comment]
> we could add that there's a required scanning process

Yep, that's what I was getting at.

> not sure about sites

You mean Pages? That's no longer a separate thing, right?

**Comment by wslack** [comment]
> You mean Pages? That's no longer a separate thing, right?

I was thinking of sites.usa.gov; you're correct it needs an update. Will add this for todos this week.

**Comment by wslack** [comment]
The section linked to is gone and the content lives, updated, at https://before-you-ship.18f.gov/ (bottom of homepage). Anything wrong with that? Perhaps we can close.

**Comment by afeld** [comment]
@wslack I'd frame the acceptance criteria as

* [ ] As a [potential] Federalist user, I know what to do to get my site ATO'd

That section doesn't give (concrete) steps to do so at the moment.

**Comment by wslack** [comment]
Oh, so you want this part to have the instructions? Should that really be on the homepage or should I make a subprogram?

**Comment by afeld** [comment]
No strong feelings about where it lives, as long as it's written down somewhere and included / linked to from Before You Ship.

**Comment by wslack** [comment]
https://federalist-docs.18f.gov/pages/how-federalist-works/custom-urls/ has the customer-facing instructions; should we just link to those or do you want more ATO-specific info?

**Comment by afeld** [comment]
Ha, oh yeah! Simple as that.
