### ISSUE TITLE
update/expand guidance around auth

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#275]
[From Slack](https://gsa-tts.slack.com/archives/ato-sprinting-team/p1488579604000019):

> @afeld: a question came up for OMB eRegs: if a system has an admin section, does that require MFA? would having it restricted to an IP range make any difference?
>
> @NoahKunin: Yes, for Low and Moderate systems I’d say that’s absolutely required. Contextual for Open data systems, given their importance, and if we’re talking about an alpha/beta vs full production. Now that we have a workable Single Sign On implementation, the answer is almost always going to be yes.
>
> No, in regards to IP filtering. I’m not going to accept that as a factor in MFA.

**Comment by afeld** [comment]
Clarified over video chat: The distinction is that for Open Data systems, they can make their production site public "as soon as they enter the assessment phase", whereas others will only make their staging site public (for penetration testing).

**Comment by NoahKunin** [comment]
Huh! I was so certain this was in the control baseline already. Given how many ATOs we've done, I'm shocked it isn't, and it's just been my AO demand the whole time. Well heck, that's on me. On it.
