### ISSUE TITLE
Conduct user testing on Before You Ship guide

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#276]
We've made some big content changes to the guide, we should do user testing. 

For example, the hypothesis is that extra information about FISMA and NIST isn't useful to the majority of the audience. An appendix with links should suffice, and simplifying the reading path to actionable information will pay off.

**Comment by afeld** [comment]
Some suggestions on the information architecture: https://docs.google.com/document/d/1NpnG3rHS1OpSMtr34suEiXwwCYbc_Xar0ItFw67FEh4/edit

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
