### ISSUE TITLE
Open data systems still a thing?

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#279]
The before you ship guide defines and Open Data system. Is that still a thing we do, and how do we codify that with the LATO guide?

**Comment by hollyallen** [comment]
Noah uses "open data system" as a way change what he allowed during pre-authorization. When the ATO assessment starts, then low, moderate, or high are used for the impact level.

**Comment by hollyallen** [comment]
PR #280

**Comment by NoahKunin** [comment]
Closing here, work will occur on the PR.
