### ISSUE TITLE
Add text about required logging

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#284]
Here is the information all of our applications need to log:

AU-2a Parameter Requirement: Successful and unsuccessful account logon events, account management events, object access, policy change, privilege functions, process tracking, and system events.  For Web applications: all administrator activity, authentication checks, authorization checks, data deletions, data access, data changes, and permission changes.

**Comment by afeld** [comment]
Also important that the events are traceable back to the user that performed them (if possible), so include things like the user ID.

We may also want to give guidance about how to do logging that will work best with Kibana, since we'll need projects to set up certain filters/charts. For example: logging in JSON may be preferable.

**Comment by afeld** [comment]
Note to self: reach out to @rogeruiz and @wjwoodson for Kibana usage help.

**Comment by afeld** [comment]
https://github.com/18F/logsearch-for-cloudfoundry#readme

**Comment by rogeruiz** [comment]
Another [good resource here are the filters which transform the firehose](https://github.com/18F/logsearch-for-cloudfoundry/tree/master/src/logsearch-config/src/logstash-filters/snippets) before putting things into ES.

**Comment by afeld** [comment]
Per @yozlet [in Slack](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1493751995549427?thread_ts=1493747235.502953&cid=C09CR1Q9Z), logging JSON from an application on cloud.gov won't show up at https://logs.fr.cloud.gov at the moment.

> [@LinuxBozo] figures it’s an issue with the LogStash configuration. Unfortunately this is a not an easy thing to debug

**Comment by afeld** [comment]
[cloud.gov logging documentation](https://cloud.gov/docs/apps/logs/#web-based-logs-with-historic-log-data)

@LinuxBozo Is there an issue on the cloud.gov side around the JSON parsing we can cross-reference here?

**Comment by mogul** [comment]
We've got [a card in Favro representing this problem](https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-5153) now. It's in the urgent/blocking lane for the cloud.gov Platform Squad.

**Comment by mogul** [comment]
(Deprioritized a bit based on Aidan's feedback... Likely to be resolved around the end of next week given current team velocity.)

**Comment by NoahKunin** [comment]
@mogul I'll check back in 2 weeks just to give ya'll space, since whatever is currently the case didn't seem to block FEC...

**Comment by LinuxBozo** [comment]
For awareness, the JSON structured logging issue in cloud.gov was resolved at the end of June.

**Comment by jseppi** [comment]
Suggest getting this added to the guide in some form, even if it is not complete with the guidance/ability to use JSON, because it just came up in the CALC assessment and now we're hustling to add the required logging.

**Comment by afeld** [comment]
Discussion about alerting in cloud.gov: https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1490122821888829
