### ISSUE TITLE
Add "ATO Reviewer" as role

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#287]
The "ATO Reviewers" are those that assess the software environment and SSP. Includes ISSO, ISSM, penetration testers, and those who test the SSP.

**Comment by NoahKunin** [comment]
@hollyallen ...as a role...to the SSP template? So people know they will add someone to their admin pages?

**Comment by afeld** [comment]
I think she means somewhere under https://before-you-ship.18f.gov/ato/. We have gotten feedback from project teams that they don't understand who the folks are who will be involved in the sprint, role-wise. My thinking was to have Before You Ship briefly explain what each of those acronyms are, what they are responsible for, etc.

**Comment by NoahKunin** [comment]
Ok, I think there's a logical place for this. On it.
