### ISSUE TITLE
mention the test cases

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#293]
CALC ones, which can/should be generalized:

https://docs.google.com/spreadsheets/d/18aZNXBaQrq2gIas3-1oLSlokefB8RibWp8wID70qfic/edit#gid=1541480683

Maybe as part of [the walkthrough](https://docs.google.com/spreadsheets/d/18aZNXBaQrq2gIas3-1oLSlokefB8RibWp8wID70qfic/edit#gid=1541480683)?

**Comment by NoahKunin** [comment]
@afeld Still says `draft`, and since there is only 1 more control for Moderate, we should just give a single test case format. I looked for the final set in the FEC older, and via search. No 🎲. Do you or @hollyallen know where they are?

**Comment by afeld** [comment]
I was out for a lot of the FEC assessment, so not entirely sure. Found another spreadsheet: [Assessment Cases for moderate applications on cloud.gov](https://docs.google.com/spreadsheets/d/1xYv9PHk6P1ePHSQcJWXSAYbAvmxzSsDOZrdS285DKYY/edit?ts=58eba80c#gid=1541480683)

> since there is only 1 more control for Moderate, we should just give a single test case format

![noice](https://media.tenor.co/images/d2c70f7f64587dc3b7c86ee06756fb4a/tenor.gif)

**Comment by NoahKunin** [comment]
Great! On it.
