### ISSUE TITLE
au-2 logging requirements

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#296]
Add in this list of things that must be logged.

Audit Events (AU-2) : Determines that the information system is capable of auditing the following events: [Assignment: organization-defined auditable events];

AU-2a Parameter Requirement: Successful and unsuccessful account logon events, account management events, object access, policy change, privilege functions, process tracking, and system events.  For Web applications: all administrator activity, authentication checks, authorization checks, data deletions, data access, data changes, and permission changes.

**Comment by afeld** [comment]
Duplicate of #284.

**Comment by hollyallen** [comment]
Thanks! Amazing.
