### ISSUE TITLE
correct the PII page

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#304]
From @vzvenyach:

> OGC brought to my attention some language in the Before You Ship guide around PII (https://pages.18f.gov/before-you-ship/security/pii/) that they believe is incorrect. I suggested that we'd work with Richard Speidel to address the concerns.

Working with @rspeidel to determine

* What is incorrect/missing
* What additional resources we can link to
    * He already mentioned [OMB Circular A-130](https://obamawhitehouse.archives.gov/sites/default/files/omb/assets/OMB/circulars/a130/a130revised.pdf)
* If this page can be replaced with a link to a more canonical resource, which is similarly terse/actionable/plain-language

/cc @andrewmaier

**Comment by afeld** [comment]
Notes from conversation with Richard Speidel [here](https://docs.google.com/document/d/1oYBS2wXLl1AaXzd8cYF0Q7l5avGJ9r_aZlyWOPay0Wg/edit#heading=h.mck5975j3lva).

/cc @andrewmaier

**Comment by andrewmaier** [comment]
Setting up some time to chat with @bradnunnally tomorrow.

**Comment by andrewmaier** [comment]
@afeld @hollyallen Just chatted with @bradnunnally, so he's aware. He suggests making a (micro)staffing request. [My next fulltime project](https://github.com/18F/staffing-and-resources/issues/324) starts mid June, for what it's worth
