### ISSUE TITLE
"Before You Ship" implies that the guide is only needed last-minute

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#305]
We have gotten feedback for a long time that the name of the guide is misleading, giving teams the impression that they only need to worry about the content as they approach their launch date, not from when they start development (or earlier). A couple of ways we could tackle this:

* Rename the guide
    * Very open to name ideas!
* Require (part of?) the guide is read as part of onboarding for some subset of 18F hires (Engineering + Product?)

I could have sworn there was an issue around this already, but can't find it.

**Comment by NoahKunin** [comment]
@afeld Would outcomes be any different? Even when we tell people the process can take 6-8 weeks, behavior doesn't change. And I'm not even sure what behavior we are looking for. We do client based work, where the Product and Biz Owners are external entities. They will never put ATO related work "first". And even if they tried - how could you document a system before it was actually legit ready for an alpha or beta release?

**Comment by afeld** [comment]
All fair counterpoints. Maybe this could be a potential outcome of #276?

**Comment by its-a-lisa** [comment]
Deleting as stale based on the TTS Tech Portfolio Deep Grooming session from 3/30/20; if you have any questions, comments or concerns, please let us know either in the #infrastructure or #tts-tech-portfolio slack channels
