### ISSUE TITLE
any forms should include a Privacy Act notice

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#312]
From @rspeidel:

> we [must] include the minimum requirements below: 
>
> 1. the (A) the authority (whether granted by statute, or by executive order of the President) which authorizes the solicitation of the information and whether disclosure of such information is mandatory or voluntary;
> 2. (B) the principal purpose or purposes for which the information is intended to be used;
> 3. (C) the routine uses which may be made of the information as published pursuant to paragraph (4)(D) of this subsection (this may be included by reference to the SORN)
> 4. and (D) the effects on him, if any, of not providing all or any part of the requested information.
>
> https://www.justice.gov/opcl/agency-requirements#e3

I don't understand what any of that means; hoping to get more clarification from him 😄 

/cc @andrewmaier

**Comment by andrewmaier** [comment]
These requirements follow from the Privacy Act, of which @cydharrell created [a helpful summary](https://docs.google.com/document/d/1UN40GsmncnKZHIdIiYwqzkqTuN3A-atkTDvYx4B_vEo/edit) while working on the Federal Front Door InfoSharing project. 

My familiarity with these requirements stems from my work in considering the privacy implications of 18F's design research practice — specifically my work in helping to get an Ethnio/recruiter replacement. For that, Lauren Ancona, @esgoodman, @onezerojeremy, Richard and I have collaboratively came up with [this prototype](https://feedbackmvp-demo.app.cloud.gov/) and [this Privacy Act statement](https://docs.google.com/document/d/1j6jijIg3QiSX9jyDPwad2b6_tKkPvQ2HG3MpYv00p4U/edit#), the later of which should soon to be published on GSA.gov.

**Comment by andrewmaier** [comment]
It looks like this information already has somewhat of a home on [the PII page](https://before-you-ship.18f.gov/privacy/pii/). I'm going to review the PII pages from [this content inventory](https://docs.google.com/spreadsheets/d/1fvMGqhY8ula0mFSwCsoPZrTUjCXamZDNaCzC48Jj_48/edit#gid=0) and the "Your Role and the Privacy Act" page on InSite. I'll draft any necessary updates and run those by @rspeidel.

**Comment by afeld** [comment]
This will come up as part of contacting the Privacy office, so good for now.
