### ISSUE TITLE
As a project team, I want to know how to get my RoE and Project Plan signed

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#313]
Would be helpful to add explicit instructions / checklist items. I've never actually done this before, so not sure what's involved.

**Comment by NoahKunin** [comment]
Is GSA IT making you sign the Project Plan too? That seems like crazy overkill.

**Comment by afeld** [comment]
Yes, though I don't really understand the point of that document.

**Comment by hollyallen** [comment]
We've since learned we don't need a project plan, but getting an ROE signed is still a thing.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
