### ISSUE TITLE
As a sprinting team, we need to notify the platform of upcoming penetration testing

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#314]
Sounds like we need to let the cloud.gov team know when we are going to start a penetration test, providing the IP(s) of the penetration testing machines, so that they can submit a ticket to AWS. Also, we may need to think about how to offboard penetration testing IPs, though that may be a separate task.

**Comment by NoahKunin** [comment]
Slight alteration. We shouldn't notify cloud.gov of a _particular_ pen test. They just need an always update list of source IPs. So onboard/offboard should be the same task, and really, needs to be the responsibility of GSA IT. That's not the job of BYS, and those IPs should not be public.

**Comment by afeld** [comment]
> We shouldn't notify cloud.gov of a particular pen test.

@hollyallen Is that your understanding as well?

**Comment by mogul** [comment]
Bad people can always probe us from the public in any case. 

I think the main thing is to limit the scope of the testing to the stuff that's in the customer's responsibility, and trust us to test the stuff that's in our scope. 

They also need to recognize that if they hammer us performance-wise they may get throttled. It's nice to have a heads-up so we can remind people about that, and so if it does happen we know what's up.
