### ISSUE TITLE
Static Security analysis: ESLint rule change

### ISSUE THREAD

**Issue by mozfreddyb** [18F/before-you-ship#320]
Heya,

I work on the ESLint rule `eslint-plugin-no-unsafe-innerhtml`, that you mention in your static analysis rules.
We just updated the codebase (also to make it more ocnfigurable) and would suggest you use the new add-on which is https://github.com/mozilla/eslint-plugin-no-unsanitized

Thanks!

**Comment by afeld** [comment]
Nice, thanks for letting us know! You might want to officially [deprecate](https://docs.npmjs.com/cli/deprecate) the old one, if you haven't already.

**Comment by mozfreddyb** [comment]
Yeah, we do!
We need to ramp up our documentation for projects migrating to the new rule. That's gotta happen first.

**Comment by afeld** [comment]
Gotcha. I hadn't realized that `eslint-plugin-no-unsafe-innerhtml` is a [`dependency`](https://github.com/mozfreddyb/eslint-config-scanjs/blob/master/package.json) of `eslint-config-scanjs`...should we just recommend that folks use the latter? Also, I'm not sure if you saw [our example `.eslintrc`](https://github.com/18F/compliance-toolkit/blob/master/configs/static/.eslintrc), but I would really like a) to have that somewhere more canonical, and b) for 18F to not have to maintain that file ourselves. Any interest in incorporating it into the READMEs of the respective projects, if that configuration is even needed at all?

**Comment by mozfreddyb** [comment]
Oh, right.
Note that `eslint-config-scanjs` is not well suited for use in continuous integration. It alerts often and early. The idea is to guide manual inspection and security analysis.
That said, if you want to recommend eslint-config-scanjs, you don't need to suggest eslint-plugin-no-unsafe-innerhtml.

**Comment by NoahKunin** [comment]
Leaving the issue of a canonical `.eslintrc` storage to another issue if someone wants to take it on. Feels out of the scope of this repo. However, I am fixing the instructions in the guide now.

**Comment by jseppi** [comment]
FYI - the rules available in `eslint-plugin-scanjs-rules` are currently changing some more (mostly non-necessary FirefoxOS rules being removed), so the sample eslint config referenced in BYS will need to be updated. 

The package is actually broken as of right now, but I have a PR in to fix it: https://github.com/mozfreddyb/eslint-plugin-scanjs-rules/pull/11

**Comment by afeld** [comment]
@mozfreddyb @jseppi Ignoring what's in the guide currently, what would you recommend to folks as baseline JS scanning to set up in continuous integration, in terms of services, packages, and/or config settings?

**Comment by jseppi** [comment]
I'm not well researched in this area. Node Security Project looks promising though: https://nodesecurity.io/

**Comment by afeld** [comment]
Whoa, @jkohrman created a package based on our recommendations: https://www.npmjs.com/package/eslint-config-secure

**Comment by mozfreddyb** [comment]
I'm using no-unsanitized in CI and https://github.com/mozfreddyb/eslint-config-scanjs to aid manual testing. The former is very precise and the latter is prone to show lots of false positives, but makes manual analysis much easier. Haven't looked at nodesecurity products.
