### ISSUE TITLE
Do I need to include basic auth for a public prototype?

### ISSUE THREAD

**Issue by adborden** [18F/before-you-ship#328]
I'm building dynamic prototypes to use in usability sessions or get public feedback. I only have 3-4 weeks to build and test these prototypes. Most prototypes have no back end to store any data and will be implemented as static HTML/CSS/Javascript; possibly with the static buildpack on cloud.gov. The prototypes might include forms that collect PII, but the data is not persisted anywhere. I can include a disclaimer so users don't use real PII. The prototype only includes information that is already public and non-confidential.

I meet the conditions for [pre-assessment](https://before-you-ship.18f.gov/ato/types/#conditions-for-pre-assessment) but do I need to? The intention is that this system will never go through ATO and adding Basic auth makes it difficult to get public feedback.

**Comment by hollyallen** [comment]
Yes, you do have to include basic auth. The reason is that without basic auth it is accessible to anyone on the public internet, and is therefore a production government system and would required an ATO. Sorry.

**Comment by afeld** [comment]
Alternatively, you can put the site on Federalist, and get the site scanned in a day or so to be publicly accessible.

/cc @wslack

**Comment by wslack** [comment]
Bingo. Federalist should be able to handle those.

@adborden can you use artifacts from the USWDS to build these prototypes? (this would be great since those components already have a 👍 on Federalist - we had to specifically white flag the forms)

**Comment by adborden** [comment]
Anything we launch to our `sandbox-gsa` account would also be accessible to the public internet, even if we're just using it for development, or testing deployment scripts. Do that make it a production government system and therefore we need basic auth for those too?

**Comment by adborden** [comment]
@afeld @wslack That's great, but some IAAs don't include provisions for Federalist, in this case, our only option is cloud.gov. Might be good to make sure Federalist is included for Discovery focused projects.

**Comment by adborden** [comment]
It would also be nice if static buildpack based apps on cloud.gov were also covered by some existing ATO, I'm not sure how technically its any different than Federalist, static pages being added to an existing system.

**Comment by afeld** [comment]
Yeah, fast-tracking ATOs for certain types of "apps" on cloud.gov is very likely something to come out of the ATO Sprinting Team.
