### ISSUE TITLE
Make ATO process more user friendly

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#333]
Folks are still finding the ATO process hard to understand and navigate. Ideas presented in a recent meeting include:

1. An easy to understand walkthrough of the process
2. Model library of the docs
3. List of responsibilities and expectations for the point person from the project
4. Annotated version of the kinds of questions asked during the assessment process

**Comment by enbarrygit** [comment]
Hi,
I would like to know how to actually access the docs. I always get prompted for a google docs access request form.
Would be great if one could access the library

Thanks 
EB

**Comment by afeld** [comment]
@enbarrygit Please send an email with more details about what you're looking for: aidan.feldman@gsa.gov. Thanks!

**Comment by afeld** [comment]
A laudable goal we should constantly strive for, but closing as stale / not actionable.
