### ISSUE TITLE
Remove "Good Production Practices" page

### ISSUE THREAD

**Issue by adborden** [18F/before-you-ship#353]
The [Good Production Practices page](https://before-you-ship.18f.gov/infrastructure/good-production-practices/) isn't organized very well. The information should probably be moved elsewhere or we could spend some effort to clean it up. My preference would be to remove it for now as I don't think anything in there currently is pertinent.

Some concrete feedback:

- It contains a list of good practices in addition to "must-haves". The "must-haves" probably should be in a checklist or another page because people looking for must-haves wouldn't think to look in something called "good practices".
- Good practices are organized by topic which seems good, but some of those topics (Logging and Monitoring) just link elsewhere. The good practices should probably be written out for these sections and then a link to more details could link to the Logging and Monitoring pages.
- (I believe) 18F should be using cloud.gov unless the project calls for something different. The best practices are written from the perspective that you are rolling your own infrastructure or running on AWS.
- Similarly, the language used isn't the same language that I see in slack, on 18F projects, or in other 18F documentation. e.g. alpha/beta/blue-green vs. development/staging/production.
- The good practices are brief and there's no examples. Some of these good practices are a bit cryptic. e.g. "Expected exposure for alpha/beta/blue-green environments is enforced" means... ?

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
