### ISSUE TITLE
What is the definition of a "system"?

### ISSUE THREAD

**Issue by adborden** [18F/before-you-ship#354]
I don't understand what defines a "system", so I have trouble understanding what requires an ATO and what does not (and maybe the definition of system alone doesn't answer the question "do I need an ATO?"). Some examples:
- CMS
- production static website for a partner
- static website describing research findings
- dynamic prototype
- styleguide for developers and designers
- developer documentation site for an npm module or command line tool
- README on github

**Comment by afeld** [comment]
Haha, that's a fun question that @NoahKunin liked to rant about 😄  

> 'Information system' means a discrete set of information resources organized for the collection, processing, maintenance, use, sharing, dissemination, or disposition of information

https://a130.cio.gov/definitions/

A note written on a napkin is a "a discrete information resource for the sharing of information", so...yeah.

**Comment by adborden** [comment]
Oh right, government :sweat_smile: Well, I suppose having that definition is helpful context. Mind if I add it to this [page](https://before-you-ship.18f.gov/ato/) after "Key roles"?

**Comment by afeld** [comment]
Go for it!

**Comment by wslack** [comment]
I can only imagine a court case where someone tried to adjudicate that definition. 😆

**Comment by thecapacity** [comment]
@wslack it's actually defined in US Code; https://www.law.cornell.edu/uscode/text/44/3502

A-130 just quotes that... so yea it was probably adjudicated at some point.

**Comment by wslack** [comment]
Would love to read that transcript.
