### ISSUE TITLE
document RA-5 requirement for applications

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#362]
> medium term solution of configuring our cloud.gov applications to at least “restage” two times a week or more

https://docs.google.com/document/d/10mwfDZjb7UWHBmVUheYDyPb1l3Xot8v_fwNbOabKxV0/edit#heading=h.5vrhnl4y4400

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
