### ISSUE TITLE
should we create an issue template checklist for everything in index?

### ISSUE THREAD

**Issue by leahbannon** [18F/before-you-ship#37]

**Comment by afeld** [comment]
Hmm. I like the idea, though

* Not all of our projects use GitHub for task management.
* A lot of the items probably make sense as standalone tasks, especially since they won't all be completed at once.

Not sure if it's worth it.

**Comment by afeld** [comment]
https://github.com/18F/checklistomania might be worth looking into.

/cc @anthonygarvan

**Comment by leahbannon** [comment]
yeah, it might be overkill - I'm closing this for now, at least
