### ISSUE TITLE
Links from Before You Ship to the Product Guide are ending in a 404

### ISSUE THREAD

**Issue by PabbyG** [18F/before-you-ship#382]
The Product Guide is returning 404s. Any links from the Before you ship to the Product Guide are ending in this 404 experience.

Steps to reproduce:
1. Go to https://before-you-ship.18f.gov/
2. Click on "the Lifecycle section of 18F’s Product Guide" link, "https://product-guide.18f.gov/lifecycle-of-a-project/"

Error: 404 page from the Product Guide

**Comment by trevorbryant** [comment]
Unproductive, but responding for emphasis. Discovered the broken link when sharing examples of success with a customer.
