### ISSUE TITLE
rewrite AWS guide

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#40]
https://pages.18f.gov/before-you-ship/infrastructure/aws/

With the move to Cloud Foundry, relatively few developers are given (or need) direct access to AWS. 

* [x] Change the AWS guide to reflect this.
* [x] Add section about when/how to grant access to new users.

**Comment by jezhumble** [comment]
I'm in the middle of rewriting the AWS section right now

On Thursday, June 30, 2016, Aidan Feldman <notifications@github.com> wrote:

> /cc @jezhumble <https://github.com/jezhumble>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/before-you-ship/issues/40#issuecomment-229853769>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAJeOm3Er7GLo2GbqjtB8dpN-ejrS-W5ks5qRJ3ogaJpZM4G4sJQ>
> .
>


-- 
Jez Humble
Deputy Director of Delivery Architecture and Infrastructure Services
GSA Technology Transformation Service
(510) 501-9431
50 UN Plaza
San Francisco, CA 94102

**Comment by afeld** [comment]
Fixed by https://github.com/18F/before-you-ship/pull/185.
