### ISSUE TITLE
incorporate uptime monitoring into the checklists

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#400]
- https://before-you-ship.18f.gov/ato/checklist/
- https://before-you-ship.18f.gov/infrastructure/decommissioning/

## Acceptance Criteria
- [ ] Uptime monitoring documented solutions/alternatives
- [ ] Uptime monitoring added to checklist

**Comment by afeld** [comment]
Just learned we are using Uptrends in various places as well. We should probably consolidate.

**Comment by JJediny** [comment]
related https://github.com/18F/tts-tech-portfolio/issues/66

**Comment by its-a-lisa** [comment]
Moved to waiting until the [BYS is merged with Handbook](https://github.com/18F/before-you-ship/issues/421)

**Comment by afeld** [comment]
Going a different direction with this, handling uptime monitoring centrally through [centralized monitoring](https://github.com/18F/newrelic-terraform) and the #tts-tech-portfolio-alerts channel.
