### ISSUE TITLE
create visual diagram of ATO flow for TTS systems

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#41]
Can't remember who proposed this idea, but I like it.

**Comment by afeld** [comment]
Not visual, but a nice walkthrough: https://securityassessment.herokuapp.com/

**Comment by hollyallen** [comment]
https://docs.google.com/drawings/d/19prShGd9YaWTGfAMjFnbf-3xpsdoON-0k7mcKdnHk8s/edit

**Comment by JJediny** [comment]
this will come up in https://github.com/18F/tts-tech-portfolio/issues/208
