### ISSUE TITLE
link to Infrastructure Options at GSA

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#417]
https://docs.google.com/spreadsheets/d/1TTu6R9vKOR5eiyC0tjF5XfaM9ozVp0FMoKDn_ZJOxG8/edit?ts=5d9b444e#gid=0

**Comment by its-a-lisa** [comment]
Close; this is currently in the https://before-you-ship.18f.gov/infrastructure/ and I included it in my pull request to move the content to the handbook 8F/handbook#1688
