### ISSUE TITLE
Checklist says to create an Issue in archived Infrastructure repo

### ISSUE THREAD

**Issue by adborden** [18F/before-you-ship#419]
The [ATO checklist](https://github.com/18F/before-you-ship/blob/50654488851c86bf7cf94e2507970ebc7b8a663b/_pages/ato/checklist.md) links to the new issues for https://github.com/18f/infrastructure as where to create your ATO issue. Should that be updated to https://github.com/18F/tts-tech-portfolio?

**Comment by its-a-lisa** [comment]
Closing in favor of https://github.com/18F/before-you-ship/issues/421
