### ISSUE TITLE
Is the external Federalist infrastructure price correct?

### ISSUE THREAD

**Issue by tammersaleh** [18F/before-you-ship#424]
Currently reads:

> **External:** Federalist is currently offered for **$24949**/year. Check in with #federalist-business about your sales lead!

Is that correct?

https://github.com/18F/before-you-ship/blob/master/_pages/infrastructure/federalist.md#L11

**Comment by davemcorwin** [comment]
Adding @eddietejeda There are currently 2 price points for Federalist.

**Comment by eddietejeda** [comment]
That's correct
