### ISSUE TITLE
explain the different levels of ATO

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#44]
Project members should understand the criteria and implications of each.
- Open Data
- FISMA Low
- FISMA Medium
- FISMA High

@NoahKunin I'll need some help from you on this...anything you can point me to that has information already?

**Comment by afeld** [comment]
Some considerations for FISMA High in the [Product Guide](https://docs.google.com/document/d/1Jr_Bizbp4UjbINqglP86bElSWWI4XWrt7fVbFqlqNEM/edit#heading=h.t8yc7xi97tae).

**Comment by thecapacity** [comment]
Would also suggest FedRAMP and inherited controls:

* https://www.fismacenter.com/fedrampmemo.pdf
* http://csrc.nist.gov/groups/SMA/forum/documents/june2013_presentations/forum_june2013_mgoodrich.pdf

**Comment by afeld** [comment]
Per @emaland, 

> SSNs != FISMA High
> 
> PHI (Protected Health Information) generally makes a system FISMA High by default

https://18f.slack.com/archives/devops/p1453491960002145

**Comment by thecapacity** [comment]
For background on FISMA, FIPS 199 is the reference to "develop standards for categorizing information
and information systems" - i.e. what makes HIGH/MED/LOW (across the three facets).

http://csrc.nist.gov/publications/fips/fips199/FIPS-PUB-199-final.pdf

**Comment by afeld** [comment]
I think we're ok on this now.

https://before-you-ship.18f.gov/ato/types/
