### ISSUE TITLE
incorporate the ATOs at TTS deck (task)

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#446]
Follow-up to https://github.com/18F/before-you-ship/issues/420#issuecomment-567287462.

https://docs.google.com/presentation/d/1IJurX7Jc5XAQqmJSZtGZeJ8pk3IMfEIMRh1frmCpHlA/edit

That deck is great, and we should incorporate that content into Before You Ship (or the OpenControl ATO Guide) proper.

cc @LindsayYoung

**Comment by LindsayYoung** [comment]
That would be wonderful! Tell me if there are ways I can help

**Comment by its-a-lisa-at-work** [comment]
@afeld adding you to this card because I also added you as a reviewer to the pull request https://github.com/18F/before-you-ship/pull/487
