### ISSUE TITLE
broken link for a11y review signup

### ISSUE THREAD

**Issue by gbinal** [18F/before-you-ship#449]
On https://before-you-ship.18f.gov/laws/508/, the link to request an `Accessibility Review` is broken.  

The destination link is https://github.com/18F/Accessibility_Reviews, which may actually exist but I don't have permissions.  If so, we should add a mention to ask for access in #admins-github if one doesn't have access.

**Comment by afeld** [comment]
Not sure if they're A Thing anymore; [checking](https://gsa-tts.slack.com/archives/C02BT4H5Q/p1594684613335300).

**Comment by iamjolly** [comment]
I'm happy to take this issue and work on a PR which includes more current guidance on this. Accessibility reviews are indeed still a thing, but the options and process needs clarification.
