### ISSUE TITLE
incorporate ATO/ATU Tech Talk deck

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#456]
[Deck](https://gsa-tts.slack.com/archives/CG8SNAEQM/p1589999263159100?thread_ts=1589994148.158600&cid=CG8SNAEQM)

## Background information

cc https://github.com/18F/before-you-ship/issues/446

## User stories

As someone going to Before-You-Ship, I would like to have the most up to date information so that I am better able to do my job

## Acceptance criteria

- Before-You-Ship explains the distinction between ATOs and ATUs

---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
@afeld can you say more about this? Is this just simply linking the doc within Before You Ship -- or extracting some of the information and adding it directly to the pages as content?

**Comment by afeld** [comment]
I'd say the latter is ideal, but the former is better than nothing.
