### ISSUE TITLE
Migrating content from Hub to AWS part of Before You Ship

### ISSUE THREAD

**Issue by melodykramer** [18F/before-you-ship#49]
hi all! There are a number of pages on the Hub that concern Infrastructure guidelines or AWS: 
​
https://hub.18f.gov/aws-access/index.html
https://hub.18f.gov/encrypt-pers-comp/index.html
https://hub.18f.gov/guidelines/index.html
https://hub.18f.gov/cloud-foundry/index.html
​
I would like to propose that some of this information would be better if it lived here:
​
https://pages.18f.gov/before-you-ship/infrastructure/aws/

or on the Infrastructure page on the Handbook - https://github.com/18F/handbook/blob/staging/articles/2-about-us/teams/infrastructure.md
​
Are there objections to moving this content? I want to make sure we account for it as we're completing this migration, and I want to make sure it doesn't overlap with existing content. I would much rather point to this source and the Handbook page for Devops/Infrastructure than to have small islands of content floating around the Hub.

**Comment by melodykramer** [comment]
https://hub.18f.gov/standards/terms-and-conditions/index.html also seems like it should belong here, maybe.

**Comment by afeld** [comment]
Seems that the information that was in the Hub is so out-of-date that it's not even worth trying to migrate. Forward!
