### ISSUE TITLE
unrendered markdown adding extra spaces

### ISSUE THREAD

**Issue by leahbannon** [18F/before-you-ship#52]
Currently, there are extra spaces in the way we're displaying unrendered markdown for copy and pasting to issues. So if you copy and paste into an issue, you're creating sub-bullets.

This is an issue for the accessibility issue text from the index.md file, but not the ATO one.

**Comment by afeld** [comment]
Ah ok, so specifically the Accessibility checklist under https://pages.18f.gov/before-you-ship/#technical, yeah? https://github.com/18F/Accessibility_Reviews/pull/8 moves that checklist into the Accessibility Reviews README, so let's call this one a `won't fix`.

**Comment by afeld** [comment]
i.e. let's not bother trying to fix it here since it will be removed soon

**Comment by leahbannon** [comment]
ok sounds good -- although there may be a bunch of extra spaces to fix in that PR, too
