### ISSUE TITLE
Would a task timeline overview page be helpful?

### ISSUE THREAD

**Issue by DavidEBest** [18F/before-you-ship#57]
The page is called before you ship, but it catalogs a lot of tasks that should begin almost as soon as a project itself begins. To emphasize that, would it be helpful if we compiled a 'Working Backwards' task timeline for this information?

The scale & tasks are obviously different, but I find the Startup Weekend Task Timeline (http://organizer.startupweekend.org/) super helpful when organizing events.

**Comment by afeld** [comment]
:+1: We should see how much of that is in the PM guide already and make sure not to overlap too much.

/cc @leahbannon @annahsebok

**Comment by afeld** [comment]
Also worth noting that anything aside from ATOs would not be part of the Compliance Toolkit work.

**Comment by DavidEBest** [comment]
Good point. :)

**Comment by annahsebok** [comment]
It's not. All the PM guide does re ATOs is point to the ATO guide.

On Wednesday, January 6, 2016, David Best <notifications@github.com> wrote:

> Good point. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/before-you-ship/issues/57#issuecomment-169514482>.
>


-- 


Anna Heller Sebok
18F Innovation Operations Specialist
General Services Administration
1800 F Street NW
Washington, DC 20006
202.403.7245
anna.sebok@gsa.gov

**Comment by afeld** [comment]
@annahsebok Right - I meant more broadly, as the initial description here didn't say anything about ATOs.

**Comment by DavidEBest** [comment]
@afeld, @annahsebok I'm not looking to do this ASAP, and I'm not suggesting it should be rolled into the Compliance Toolkit work. I find the format useful and wanted to get some other thoughts on it. :)

I like the way the one above categorizes tasks by type (or person). It makes it easier to filter tasks by type (here are all the ATO/Outreach/O&M Prep tasks, as they should be done) or time (we want to release in 2 months, what needs to start NOW).

This works pretty well when planning for events; it seems like it might translate to shipping a product. Thoughts?

**Comment by afeld** [comment]
:+1:

Also might be worth considering using https://github.com/18F/checklistomania.

**Comment by DavidEBest** [comment]
I didn't know that was a thing. So many repos... I'll see what that's all about.

**Comment by leahbannon** [comment]
If you can compile a timeline, I support you and I'd be happy to review a draft. I found that since many things also need to be done periodically, that was tough. Also pretty controversial. So I wanted to specifically avoid the checklist mentality (except for maybe the subsequent release list).
