### ISSUE TITLE
Add a link to this Guide from the Hub

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#6]
Not sure if this warrants its own repo...thoughts?

**Comment by gbinal** [comment]
I think it's not a problem.  Especially if you make it a guide, re: #8

**Comment by afeld** [comment]
The one nice thing about it being in the Hub is that it comes up in search. We should link to it, at the very least.

**Comment by NoahKunin** [comment]
@afeld link from Hub yes for search, but should be a guide because tons of external teams need this too.

**Comment by DavidEBest** [comment]
@afeld Now that the information has been moved out of the hub, is okay to close this one?
