### ISSUE TITLE
document NIST controls

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#64]
At the very least, link out to wherever's relevant.

* [RA-5(a) - Vulnerability Scanning](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=RA-5)
* [SA-11 (1) - Developer Security Testing and Evaluation | Static Code Analysis](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=SA-11)
* https://web.nvd.nist.gov/view/800-53/Rev4/impact?impactName=moderate

@NoahKunin What was the third one you mentioned?

**Comment by DavidEBest** [comment]
CA-8 is Penetration Testing (https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=CA-8). Perhaps that's the one?

**Comment by DavidEBest** [comment]
Is this covered by #90?

**Comment by afeld** [comment]
Works for me!
