### ISSUE TITLE
explain ATO delegation

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#65]
From @DavidEBest in [Slack](https://18f.slack.com/archives/devops/p1452287074001698):

> Whoever signs off and accepts the risk of operating an information system if you were to have built this system yourselves needs to sign the delegation letter. This person is normally called the Authorizing Official. They will have received this title through a series of delegations from the head of the [agency], presuming procedures were followed.
>
> Note this document is critical and urgent - it clarifies and stipulates that the [agency] is not the system owner, 18F/GSA is, which allows us to do both what we've done to date and to complete the work we have in front of us. Without it, there is a lack of clarity, potentially legal in nature, on who is the customer and who is the provider of this system which makes it impossible to correctly move the system through the variety of compliance requirements we have in front of us.

I know that it also came up via @wslack with the FOIA project, so would be good to have an explainer about how ATO delegation works.

/cc @leahbannon

**Comment by wslack** [comment]
Draft:

18F has two delivery modes for custom solutions for our partners.
1. Under a SaaS model, we become 100% responsible for the system as a shared service, even if there is only one (current) partner. This is in line with general GSA practice. For example, FedBizOpps does not require an ATO for every agency that uses it. While not everything is in this category, many projects may be well-suited to being offered as a service. Therefore, we ask clients to make risk-management decisions - either delegating the risk to us or working with the 18F Infrastructure team to discuss the security controls and where they are best placed. If a partner wants more security, we can add appropriate scope to projects with cost-recovery. For example, GSA made an investment in Salesforce and Gmail to get them prepared for government usage.

For example, an agency could want to raise security to DoD standards. 

In general, if offered as SaaS, we have to own the ATO. It's less an ATO delegation than formal acceptance of risk given that the TLD domain is owned by the partner (however, the domain will be formally/technically transferred to 18F). FedBizOps owns the content uploaded to it and the risk associated with it.

2. A completely separate offer is that we do everything up to risk management and the ATO, and they do the ATO. 18F solely develops and delivers software, which is then hosted and run on partner systems. We have no capacity to help with the ATO through a partner's risk management framework. We may help with a holistic risk-management transformation process, with this as a part. These are the two options.

**Comment by wslack** [comment]
@jroo, @emaland, @cscairns - Any comments or questions before I ship this off to CFPB?

**Comment by wslack** [comment]
Also I'm realizing that my text doesn't:
* Answer the original questions in the issue
* Explain why this is beneficial to an agency

**Comment by afeld** [comment]
For transfers, we should also make sure to mention how the operational responsibilities they will be inheriting (i.e. what they will need to do in cloud.gov going forward).

/cc @abisker @mogul @dlapiduz

**Comment by wslack** [comment]
Hi friends, we've been asked for something like this by CFPB. Who can help me add that language above? (Should it be a scheduled convo with Noah?)

**Comment by afeld** [comment]
@wslack Made some minor tweaks to your draft above. I'm not sure that most of that belongs on the ATO delegation page...maybe some should be in https://pages.18f.gov/intake/, since the decision about whether it's SaaS or not would presumably happen before an IAA is signed.

My original posting of the issue conflated two topics (ATO delegation and handoff of "completed" projects), so split the latter out to https://github.com/18F/before-you-ship/issues/100.
