### ISSUE TITLE
CSS overrides of the guide-style not live in production.

### ISSUE THREAD

**Issue by DavidEBest** [18F/before-you-ship#78]
I'm not sure if this is a misconfiguration in this project, or an issue with the guide-style (https://github.com/18F/guides-style), but css overrides for this guide are not appearing in production.

Locally, I see that my assets/css/styles.scss are merged into the styles:
<img width="227" alt="screenshot 2016-01-15 13 48 17" src="https://cloud.githubusercontent.com/assets/933586/12361900/c6747bcc-bb8e-11e5-8b6b-f31b56b2541f.png">

On the server, I see the raw guide styles used:
<img width="224" alt="screenshot 2016-01-15 13 48 44" src="https://cloud.githubusercontent.com/assets/933586/12361897/c4e54840-bb8e-11e5-933b-49942d9d6992.png">

Is this a misconfiguration on our part? I see a similar situation with the agile guild's page: https://pages.18f.gov/agile/

@mbland

**Comment by mbland** [comment]
So the way our Pages/Guides are deployed, it pulls the main stylesheet from `/guides-template`, as you've noticed. If you want to override the styles from that sheet, you can [define an additional style sheet and add it to a `styles:` list in `_config.yml`](https://github.com/18F/guides-style/#additional-scripts-and-styles).

I'm planning to update 18F/guides-template soon that points out more of these advanced features as an appendix.
