### ISSUE TITLE
work on a quick description of an ATO

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#84]
What we currently have on [the ATO page](https://pages.18f.gov/before-you-ship/ato/)

> An Authority to Operate (ATO) is a complicated security review process that is required before you can deploy anything on the public web. Before a system is made publicly accessible on the Internet, it must go through either the full ATO process or a 90-Day Authority to Test. If either are not yet complete, the system must have some level of authentication required for a user to enter.

has the following issues:
- The first sentence isn't entirely accurate
- It doesn't explain what the byproducts of an ATO are
- The last two sentences (maybe?) go into a bit too much detail

**Comment by NoahKunin** [comment]
Don't know where this is coming from either. ATOs have no formal definition, but I'm pretty happy with what I've already written in the past:

> In the United States, all Federal Government information systems are regulated by the Federal Information Security Management Act (FISMA). This law empowers the National Institute for Standards and Technology (NIST) to issue guidance on what security controls should exist on information systems, especially those in production.

> While nothing is completely without risk, federal agencies require systems to receive an Authority to Operate (ATO) before putting a system into production. An ATO is the final step in NIST's risk management framework. An ATO represents the agency's **acceptance of the risk presented in operating the system**, after all due diligence has been completed and reasonable controls put in place. It usually takes the form of a signed letter from a high-level agency executive, who serves as the Authorizing Official (AO).

+ the hyperlinks here: https://github.com/fisma-ready/introduction#introduction

Mild re-write for clarity here:

> In the United States, all Federal Government information systems are covered by the Federal Information Security Management Act (FISMA). This law empowers the National Institute for Standards and Technology (NIST) to issue both guidance and standards on what security controls should exist on information systems, especially those in production.

> NIST requires that Federal agencies grant an Authority to Operate (ATO) before putting a system into production. An ATO is the final step in NIST's risk management framework. An ATO represents the agency's **acceptance of the risk in operating the system**, after all due diligence has been completed and reasonable controls put in place. NIST recognizes that nothing is completely without risk. The ATO is the formal decision that the controls in place mitigate risk appropriately, and that any risk remaining in operating the system is accepted by an appropriately empowered executive. The ATO usually takes the form of a signed letter from a high-level agency executive, who serves as the Authorizing Official (AO).

I'm not thrilled with "appropriately empowered executive", so open to alternatives there. What we need to get across is that FISMA/NIST need to hold people accountable, so someone whose feet could be held to the fire needs to be the one who says "yes".

**Comment by afeld** [comment]
> Don't know where this is coming

I didn't mean any offense. I wasn't saying there _isn't_ a good definition of an ATO, just that this site doesn't have one.

> I'm pretty happy with what I've already written in the past

Cool, those look good, though I want to see if we can take a pass for [plain language](https://pages.18f.gov/content-guide/plain-language/) (maybe with the help of the [Writing Lab](https://github.com/18F/writing-lab)?). Preferences about whether to do so in https://github.com/fisma-ready/introduction#introduction, or leave that one as a more formal definition and try for a plain language version in Before You Ship?

**Comment by afeld** [comment]
@brittag I'd love some help on this!

**Comment by afeld** [comment]
Closing in favor of https://github.com/opencontrol/atos/issues/10, via #396.
