### ISSUE TITLE
rewrite the ATO background page

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#89]
The current page is a bit disjointed:

https://pages.18f.gov/before-you-ship/ato/background/

Is this information that project teams _need_ to know? 
- If so, should we put it elsewhere?
- If not, does it belong on this site?

At the very least, I think it could
- be more narrative
- give some explanation of the video
- explain how ATOs in 18F relate to those in other agencies /cc #65

**Comment by NoahKunin** [comment]
Yikes. Not a fan.

**Comment by NoahKunin** [comment]
I say :fire: it.

**Comment by jezhumble** [comment]
https://github.com/18F/before-you-ship/pull/227

**Comment by hollyallen** [comment]
Since PR #227 was merged, and other tickets cover further consolidation of content needed in this guide, I'm going to close this issue.
